// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// API Overview:
///
/// The `beyondcorp.googleapis.com` service implements the Google Cloud
/// BeyondCorp API.
///
/// Data Model:
///
/// The AppGatewaysService exposes the following resources:
///
/// * AppGateways, named as follows:
///   `projects/{project_id}/locations/{location_id}/appGateways/{app_gateway_id}`.
///
/// The AppGatewaysService service provides methods to manage
/// (create/read/update/delete) BeyondCorp AppGateways.
///
/// @Snippet(path: "AppGatewaysServiceQuickstart")
public final class AppGatewaysServiceClient: Clients.AppGatewaysServiceProtocol, Sendable {
  let inner: any Clients.AppGatewaysServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `AppGatewaysServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AppGatewaysServiceStub = try Clients.AppGatewaysServiceTransport(options)
    inner = Clients.AppGatewaysServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AppGatewaysServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists AppGateways in a given project and location.
  ///
  /// @Snippet(path: "AppGatewaysService_ListAppGateways")
  public func listAppGateways(
    request: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse {
    try await self.inner.listAppGateways(request: request, options: options)
  }

  /// Lists AppGateways in a given project and location.
  ///
  /// @Snippet(path: "AppGatewaysService_ListAppGateways")
  public func listAppGateways(
    byItem: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AppGateway, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAppGateways(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single AppGateway.
  ///
  /// @Snippet(path: "AppGatewaysService_GetAppGateway")
  public func getAppGateway(
    request: GetAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway {
    try await self.inner.getAppGateway(request: request, options: options)
  }

  /// Creates a new AppGateway in a given project and location.
  ///
  /// @Snippet(path: "AppGatewaysService_CreateAppGateway")
  public func createAppGateway(
    request: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAppGateway(request: request, options: options)
  }

  /// Creates a new AppGateway in a given project and location.
  ///
  /// @Snippet(path: "AppGatewaysService_CreateAppGateway")
  public func createAppGateway(
    withPolling: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AppGateway> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AppGateway>.State in
      return try op._extractStatus(AppGateway.self)
    }
    let rawOp = try await self.createAppGateway(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AppGateway>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single AppGateway.
  ///
  /// @Snippet(path: "AppGatewaysService_DeleteAppGateway")
  public func deleteAppGateway(
    request: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAppGateway(request: request, options: options)
  }

  /// Deletes a single AppGateway.
  ///
  /// @Snippet(path: "AppGatewaysService_DeleteAppGateway")
  public func deleteAppGateway(
    withPolling: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAppGateway(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppGatewaysService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "AppGatewaysService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "AppGatewaysService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "AppGatewaysService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "AppGatewaysService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "AppGatewaysService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppGatewaysService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppGatewaysService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppGatewaysService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppGatewaysService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AppGatewaysService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AppGatewaysServiceClient`.
  ///
  /// To mock `AppGatewaysServiceClient` change your functions to receive
  /// `some AppGatewaysServiceProtocol` or `any AppGatewaysServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AppGatewaysServiceProtocol {
    /// See `AppGatewaysServiceClient.listAppGateways`.
    func listAppGateways(request: ListAppGatewaysRequest) async throws
      -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse

    /// See `AppGatewaysServiceClient.listAppGateways`.
    func listAppGateways(
      byItem: ListAppGatewaysRequest
    ) throws -> any AsyncSequence<AppGateway, Swift.Error>

    /// See `AppGatewaysServiceClient.listAppGateways`.
    func listAppGateways(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AppGateway, Swift.Error>

    /// See `AppGatewaysServiceClient.getAppGateway`.
    func getAppGateway(request: GetAppGatewayRequest) async throws
      -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway

    /// See `AppGatewaysServiceClient.getAppGateway`.
    func getAppGateway(
      name: Swift.String,
    ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway

    /// See `AppGatewaysServiceClient.createAppGateway`.
    func createAppGateway(request: CreateAppGatewayRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppGatewaysServiceClient.createAppGateway`.
    func createAppGateway(withPolling: CreateAppGatewayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<AppGateway>

    /// See `AppGatewaysServiceClient.createAppGateway`.
    func createAppGateway(
      parent: Swift.String,
      appGateway: AppGateway?,
      appGatewayId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AppGateway>

    /// See `AppGatewaysServiceClient.deleteAppGateway`.
    func deleteAppGateway(request: DeleteAppGatewayRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AppGatewaysServiceClient.deleteAppGateway`.
    func deleteAppGateway(withPolling: DeleteAppGatewayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `AppGatewaysServiceClient.deleteAppGateway`.
    func deleteAppGateway(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AppGatewaysServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppGatewaysServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppGatewaysServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `AppGatewaysServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `AppGatewaysServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `AppGatewaysServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppGatewaysServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AppGatewaysServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppGatewaysServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppGatewaysServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `AppGatewaysServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `AppGatewaysServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `AppGatewaysServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `AppGatewaysServiceClient.listAppGateways`.
    func listAppGateways(
      request: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse

    /// See `AppGatewaysServiceClient.listAppGateways`.
    func listAppGateways(
      byItem: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AppGateway, Swift.Error>

    /// See `AppGatewaysServiceClient.getAppGateway`.
    func getAppGateway(
      request: GetAppGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway

    /// See `AppGatewaysServiceClient.createAppGateway`.
    func createAppGateway(
      request: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppGatewaysServiceClient.createAppGateway`.
    func createAppGateway(
      withPolling: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AppGateway>

    /// See `AppGatewaysServiceClient.deleteAppGateway`.
    func deleteAppGateway(
      request: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AppGatewaysServiceClient.deleteAppGateway`.
    func deleteAppGateway(
      withPolling: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AppGatewaysServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `AppGatewaysServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `AppGatewaysServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `AppGatewaysServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppGatewaysServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `AppGatewaysServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `AppGatewaysServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AppGatewaysServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AppGatewaysServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AppGatewaysServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.AppGatewaysServiceProtocol {
  public func listAppGateways(request: ListAppGatewaysRequest) async throws
    -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse
  {
    try await self.listAppGateways(request: request, options: .init())
  }

  public func listAppGateways(
    request: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAppGateways(
    byItem: ListAppGatewaysRequest
  ) throws -> any AsyncSequence<AppGateway, Swift.Error> {
    try self.listAppGateways(byItem: byItem, options: .init())
  }

  public func listAppGateways(
    byItem: ListAppGatewaysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AppGateway, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudBeyondCorpAppGatewaysV1.ListAppGatewaysResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAppGateways(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AppGateway, Swift.Error> {
    let request = ListAppGatewaysRequest().with {
      $0.parent = parent
    }
    return try self.listAppGateways(byItem: request)
  }

  public func getAppGateway(request: GetAppGatewayRequest) async throws
    -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway
  {
    try await self.getAppGateway(request: request, options: .init())
  }

  public func getAppGateway(
    request: GetAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAppGateway(
    name: Swift.String,
  ) async throws -> GoogleCloudBeyondCorpAppGatewaysV1.AppGateway {
    let request = GetAppGatewayRequest().with {
      $0.name = name
    }
    return try await self.getAppGateway(request: request)
  }

  public func createAppGateway(request: CreateAppGatewayRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAppGateway(request: request, options: .init())
  }

  public func createAppGateway(
    request: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAppGateway(withPolling: CreateAppGatewayRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AppGateway>
  {
    try await self.createAppGateway(withPolling: withPolling, options: .init())
  }

  public func createAppGateway(
    withPolling: CreateAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AppGateway> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AppGateway>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAppGateway(
    parent: Swift.String,
    appGateway: AppGateway?,
    appGatewayId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AppGateway> {
    let request = CreateAppGatewayRequest().with {
      $0.parent = parent
      $0.appGateway = appGateway
      $0.appGatewayId = appGatewayId
    }
    return try await self.createAppGateway(withPolling: request)
  }

  public func deleteAppGateway(request: DeleteAppGatewayRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAppGateway(request: request, options: .init())
  }

  public func deleteAppGateway(
    request: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAppGateway(withPolling: DeleteAppGatewayRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAppGateway(withPolling: withPolling, options: .init())
  }

  public func deleteAppGateway(
    withPolling: DeleteAppGatewayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAppGateway(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteAppGatewayRequest().with {
      $0.name = name
    }
    return try await self.deleteAppGateway(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
